### ISSUE TITLE
Second run with same parameters deletes files

### ISSUE THREAD

**Issue by rene-armida** [rene-armida/s3pub#6]
This is a real nasty behavior: when run a second time with the same parameters, it looks like `s3pub` deletes the files just uploaded the first time, even though it goes through the work to upload the files:

```
(s3pub)marmida@longan:/tmp/what$ s3pub . sdna-web-test/s3pub-test/
./adir/bfile (2/2) 100% [###########################################################] Time: 0:00:00  34.10  B/s
(s3pub)marmida@longan:/tmp/what$ /app/bin/s3cmd ls -r s3://sdna-web-test/
2015-09-09 19:55         9   s3://sdna-web-test/s3pub-test/adir/bfile
2015-09-09 19:55         6   s3://sdna-web-test/s3pub-test/afile
(s3pub)marmida@longan:/tmp/what$ s3pub . sdna-web-test/s3pub-test/       
./adir/bfile (2/2) 100% [###########################################################] Time: 0:00:00  33.78  B/s
(s3pub)marmida@longan:/tmp/what$ /app/bin/s3cmd ls -r s3://sdna-web-test/
(s3pub)marmida@longan:/tmp/what$
```

First, the files should not be modified - they should all be skipped, because the local files match the contents of the remote files.

Second, the files should certainly not be deleted. The program instead should exit without making any modifications or producing any output, even progress bar output.

**Comment by marmida** [comment]
This is a problem with destinations that end in a slash. I'll add test coverage and fix it.
